name: quick_weather_app
description: A Very Good Project created by Very Good CLI.
version: 0.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.3
  get_it: ^7.7.0
  injectable: ^2.4.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  retrofit_generator: ^8.1.2
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/
